# This script is partially copied from the ceres-solver:
# https://github.com/ceres-solver/ceres-solver/blob/master/.travis.yml

language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: focal
    sudo: required
    compiler: gcc
    env: CXX=g++-9
  - os: linux
    dist: focal
    sudo: required
    compiler: clang
    env: CXX=clang++-9
  - os: windows
  #- os: osx
    #osx_image: xcode11.2

addons:
  apt:
    packages:
    - g++-9
    - g++-10
    - clang-9
    - clang-10
    - libeigen3-dev
    - libomp-dev
    - libgtest-dev
    - libegl1-mesa-dev
    - libsdl2-dev
    - libglfw3-dev
    - libpng-dev
    - libassimp-dev
  snaps:
    - name: cmake
      confinement: classic
    
env:
  - OMP_NUM_THREADS=2
  
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; fi

  
install:
   - if [ $TRAVIS_OS_NAME = osx ]; then;
        $TRAVIS_BUILD_DIR/travis/install_travis_osx_deps.sh; 
     fi;
   - if [ $TRAVIS_OS_NAME = windows ]; then;
        export VCPKG_DIR="C:/Users/travis/vcpkg";
        export VCPKG_INSTALL_DIR="$VCPKG_DIR/installed/x64-windows";
        $TRAVIS_BUILD_DIR/travis/install_travis_windows_deps.sh;
        cd "C:/Users/travis/vcpkg";
        #travis_wait 30 ./vcpkg install assimp;
     fi;
   - if [ $TRAVIS_OS_NAME = linux ]; then;
        $TRAVIS_BUILD_DIR/travis/install_travis_linux_deps.sh; 
     fi;

before_script:
  - mkdir ~/saiga_build
  - cd ~/saiga_build
  
script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
      /snap/bin/cmake  -DCMAKE_PREFIX_PATH="/home/travis/install" $TRAVIS_BUILD_DIR 
      make -j2
      sudo make install
      ctest --output-on-failure
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "ls base"
      ls -al "C:/Users/travis/vcpkg/installed/x64-windows/"
      echo "ls bin"
      ls -al "C:/Users/travis/vcpkg/installed/x64-windows/bin"
      echo "ls lib"
      ls -al "C:/Users/travis/vcpkg/installed/x64-windows/lib"
      cmake -DCMAKE_PREFIX_PATH="C:/Users/travis/install;C:/Users/travis/vcpkg/installed/x64-windows/" -G "Visual Studio 15 2017 Win64" $TRAVIS_BUILD_DIR 
      cmake --build . -j2
    fi

notifications:
  email:
    - darius.rueckert@fau.de
