# This script is partially copied from the ceres-solver:
# https://github.com/ceres-solver/ceres-solver/blob/master/.travis.yml
#
# Test this script on
# https://config.travis-ci.com/explore
#
language: cpp

os: linux
dist: focal

jobs:
  fast_finish: true
  include:
  - name: G++
    os: linux
    dist: focal
    compiler: gcc
    env: CXX=g++
  - name: Clang 9
    os: linux
    dist: focal
    compiler: clang
    env: CXX=clang++-9
    addons:
        apt:
            sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-9 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
            packages:
            - clang-9
  - os: windows
  - name: OSX clang
    os: osx
    osx_image: xcode11.4

          
addons:
  apt:
    packages:
    - libomp-dev 
    - libegl1-mesa-dev
    - libxrandr-dev
    - libxinerama-dev
    - libglfw3
    - libxcursor-dev
    - libxi-dev
  snaps:
    - name: cmake   
      confinement: classic
    
env:
  - OMP_NUM_THREADS=2
  
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; fi

  
install:
  - git submodule update --init --recursive

before_script:
  - mkdir ~/saiga_build
  - cd ~/saiga_build
  
script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
      /snap/bin/cmake  -DCMAKE_PREFIX_PATH="/home/travis/install" -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      make -j2
      sudo make install
      ctest --output-on-failure
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake -G "Visual Studio 15 2017 Win64" -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      cmake --build . -j2
    fi

notifications:
  email:
    - darius.rueckert@fau.de
