# This script is partially copied from the ceres-solver:
# https://github.com/ceres-solver/ceres-solver/blob/master/.travis.yml
#
# Test this script on
# https://config.travis-ci.com/explore
#
language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: focal
    sudo: required
    compiler: gcc
    env: CXX=g++-9
  - os: linux
    dist: focal
    sudo: required
    compiler: clang
    env: CXX=clang++-9
  - os: windows
  #- os: osx
    #osx_image: xcode11.2

addons:
  apt:
    packages:
    - g++-9
    - g++-10
    - clang-9
    - clang-10
    - libomp-dev
    - libegl1-mesa-dev
    - libxrandr-dev
    - libxinerama-dev
    - libglfw3
  snaps:
    - name: cmake   
      confinement: classic
    
env:
  - OMP_NUM_THREADS=2
  
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; fi

  
install:
  - git submodule update --init --recursive

before_script:
  - mkdir ~/saiga_build
  - cd ~/saiga_build
  
script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then
      /snap/bin/cmake  -DCMAKE_PREFIX_PATH="/home/travis/install" -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      make -j2
      sudo make install
      ctest --output-on-failure
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake -G "Visual Studio 15 2017 Win64" -DSAIGA_USE_SUBMODULES=ON $TRAVIS_BUILD_DIR 
      cmake --build . -j2
    fi

notifications:
  email:
    - darius.rueckert@fau.de
